import fs from 'fs';

const dictionary: Record<string, string> = {
  "No estás sola": "You are not alone",
  "Más de 5 millones de mujeres empezaron como tú": "Over 5 million women started just like you",
  "¿Cuál es tu": "What is your",
  "objetivo principal": "main goal",
  "Elija un objetivo adicional": "Choose an additional goal",
  "Puedes elegir varias opciones": "You can choose multiple options",
  "Continuar": "Continue",
  "¿Qué áreas te preocupan más?": "What areas concern you the most?",
  "Por favor seleccione todas las que correspondan": "Please select all that apply",
  "Mejorar todo el cuerpo": "Improve whole body",
  "Ninguno": "None",
  "Sigue todos los cambios de tu cuerpo": "Track all your body changes",
  "y mantente joven a cualquier edad": "and stay young at any age",
  "Durante la perimenopausia y la menopausia, las mujeres experimentan un aumento significativo de la grasa corporal total y central debido a los cambios hormonales, en particular la disminución de los niveles de estrógeno.": "During perimenopause and menopause, women experience a significant increase in total and central body fat due to hormonal changes, particularly the decrease in estrogen levels.",
  "Biblioteca Nacional de Medicina": "National Library of Medicine",
  "Centro de PubMed": "PubMed Central",
  "¿Cuál es tu punto de partida?": "What is your starting point?",
  "¿Cuál es el cuerpo de tus sueños?": "What is your dream body?",
  "¿Hace cuánto tiempo estuviste en la mejor forma de tu vida?": "How long ago were you in the best shape of your life?",
  "¿Tienes alguna experiencia previa con Pilates?": "Do you have any previous experience with Pilates?",
  "Sí, lo hago a veces.": "Yes, I do sometimes.",
  "Sí, pero hace un tiempo.": "Yes, but it's been a while.",
  "No, no tengo experiencia.": "No, I have no experience.",
  "Tu cuerpo conoce los beneficios: ahora es el momento de prosperar.": "Your body knows the benefits: now is the time to thrive.",
  "Manténgase fuerte y activa en cada etapa de su vida. Nuestros programas de Pilates Asiático están diseñados para": "Stay strong and active at every stage of your life. Our Asian Pilates programs are designed to",
  "apoyar a las mujeres durante la menopausia": "support women during menopause",
  "con cuidado, constancia y resultados palpables.": "with care, consistency, and tangible results.",
  "El Pilates asiático está hecho para mujeres como tú": "Asian Pilates is made for women like you",
  "Es una forma suave de ejercicio que": "It is a gentle form of exercise that",
  "se centra en movimientos lentos y controlados para mejorar la fuerza, el equilibrio y la flexibilidad": "focuses on slow, controlled movements to improve strength, balance, and flexibility",
  ". Ideal si estás empezando, tienes sobrepeso o": ". Ideal if you are just starting out, overweight, or",
  "estás pasando por la menopausia": "going through menopause",
  ". Te sentirás más ligera, con más movilidad y más en sintonía con tu cuerpo, paso a paso.": ". You will feel lighter, more mobile, and more in tune with your body, step by step.",
  "¿Tiene usted problemas con alguno de los siguientes?": "Do you have issues with any of the following?",
  "Ninguna de las anteriores": "None of the above",
  "¿Qué tan cómodo te sientes al hacer ejercicio?": "How comfortable do you feel exercising?",
  "¡Te tenemos cubierto!": "We've got you covered!",
  "El dolor no te detendrá. Adaptaremos tu programa para favorecer un movimiento seguro y suave": "Pain won't stop you. We will adapt your program to support safe and gentle movement",
  "Lo haremos paso a paso.": "We will take it step by step.",
  "Tu programa se ajustará a tus necesidades para ayudarte a sentirte mejor y más cómodo.": "Your program will be adjusted to your needs to help you feel better and more comfortable.",
  "¡Genial!": "Great!",
  "Estás listo para avanzar: prepárate para la transformación con Pilates.": "You are ready to move forward: get ready for transformation with Pilates.",
  "¿Cuál es tu altura?": "What is your height?",
  "Por favor, ingresa un peso entre": "Please enter a weight between",
  "Su IMC es": "Your BMI is",
  ", lo cual se considera": ", which is considered",
  "Mantén una actitud positiva y concéntrate en una dieta equilibrada y en el ejercicio. Usaremos tu índice para diseñar tu plan personal y efectivo de pérdida de peso.": "Stay positive and focus on a balanced diet and exercise. We will use your index to design your personal and effective weight loss plan.",
  "¿Cuál es tu peso objetivo?": "What is your target weight?",
  "Por favor, ingresa un peso objetivo entre": "Please enter a target weight between",
  "¿Cuál es tu edad?": "What is your age?",
  "años": "years",
  "¡Guau! Nos alegra tenerte aquí, pero debes ser menor de 80 años para usar nuestro servicio y mayor de 18 años.": "Wow! We are glad to have you here, but you must be under 80 years old to use our service and over 18 years old.",
  "Te preguntamos tu edad para personalizar tu plan": "We ask your age to personalize your plan",
  "Se ha descubierto que las personas mayores tienen un porcentaje de grasa corporal mayor que las personas más jóvenes con el mismo IMC.": "It has been found that older people have a higher body fat percentage than younger people with the same BMI.",
  "¿Qué es lo más importante para usted en un programa de Pilates?": "What is most important to you in a Pilates program?",
  "¿Cómo describirías un día típico?": "How would you describe a typical day?",
  "Tu perfil está listo": "Your profile is ready",
  "Índice de masa corporal (IMC)": "Body Mass Index (BMI)",
  "Bajo peso": "Underweight",
  "Normal": "Normal",
  "Obeso": "Obese",
  "Objetivo principal": "Main goal",
  "Estilo de vida": "Lifestyle",
  "Tipo de cuerpo": "Body type",
  "Sólido y sutilmente redondeado.": "Solid and subtly rounded.",
  "El TIPO DE ENTRENAMIENTO perfecto para ti es": "The perfect WORKOUT TYPE for you is",
  "Pilates Suave": "Gentle Pilates",
  "Hemos considerado tus zonas sensibles y tu nivel de condición física.": "We have considered your sensitive areas and your fitness level.",
  "¿Qué añadirías además de Pilates?": "What would you add besides Pilates?",
  "Seleccione al menos uno": "Select at least one",
  "Ya estamos preparando tu plan personalizado": "We are already preparing your personalized plan",
  "Hemos agregado las actividades que seleccionaste a tu plan:": "We have added the activities you selected to your plan:",
  "Te ayudarán suavemente a sentirte más liviana, más móvil y más en sintonía contigo misma, en cada etapa de la menopausia.": "They will gently help you feel lighter, more mobile, and more in tune with yourself, at every stage of menopause.",
  "¿Cuánta agua bebes diariamente?": "How much water do you drink daily?",
  "¿Cuáles son tus preferencias alimentarias?": "What are your dietary preferences?",
  "¿Cuál de estos hábitos tienes?": "Which of these habits do you have?",
  "Seleccionar todo": "Select all",
  "Elija cualquier evento de la vida que haya provocado un aumento de peso.": "Choose any life event that has caused weight gain.",
  "¡Recupera tu cuerpo!": "Get your body back!",
  "¿No sabes por dónde empezar? Ya lo tenemos todo planeado.": "Don't know where to start? We have it all planned.",
  "¿No estás seguro de si podrás lograrlo? ¡Estamos listos para motivarte y apoyarte!": "Not sure if you can achieve it? We are ready to motivate and support you!",
  "El único plan que necesitarás": "The only plan you will need",
  "Según la información que has proporcionado, alcanzarás tu peso objetivo de": "Based on the information you have provided, you will reach your target weight of",
  "el 27 de diciembre de 2026.": "on December 27, 2026.",
  "Mar": "Mar",
  "Ago": "Aug",
  "Dic": "Dec",
  "Los resultados varían según el uso individual y la adherencia": "Results vary depending on individual use and adherence",
  "Creando tu plan personalizado": "Creating your personalized plan",
  "Las reseñas que se muestran en nuestro sitio web provienen de comentarios reales de clientes en diversas plataformas. Para proteger la privacidad, los nombres y las fotos pueden cambiar, pero el contenido sigue siendo auténtico.": "The reviews shown on our website come from real customer feedback on various platforms. To protect privacy, names and photos may be changed, but the content remains authentic.",
  "Cuenta": "Account",
  "Tu Plan": "Your Plan",
  "Introduce tu correo electrónico": "Enter your email",
  "Desbloquea el acceso a tu plan de Pilates Asiático": "Unlock access to your Asian Pilates plan",
  "Respetamos tu privacidad y nos tomamos muy en serio su protección: sin spam.": "We respect your privacy and take its protection very seriously: no spam.",
  "Política de privacidad": "Privacy Policy",
  "5 millones": "5 million",
  "de mujeres ya se han unido": "women have already joined",
  "Ver mi plan": "See my plan",
  "¿Cómo te llamas?": "What is your name?",
  "Tu plan de Pilates asiático está listo!": "Your Asian Pilates plan is ready!",
  "Ahora:": "Now:",
  "Hoy": "Today",
  "con Harna": "with Harna",
  "por HARNA": "by HARNA",
  "min": "min",
  "seg": "sec",
  "Ahora": "Now",
  "Peso actual": "Current weight",
  "Tu objetivo": "Your goal",
  "Peso objetivo": "Target weight",
  "La imagen no pretende representar al usuario. Los resultados pueden variar según la persona y no están garantizados": "The image is not intended to represent the user. Results may vary by person and are not guaranteed",
  "Tu Pilates Asiático": "Your Asian Pilates",
  "Plan es ¡Listo!": "Plan is Ready!",
  "Objetivo": "Goal",
  "perder peso": "lose weight",
  "1 semana": "1 week",
  "/ día": "/ day",
  "Menos de una taza de café": "Less than a cup of coffee",
  "MÁS POPULAR": "MOST POPULAR",
  "4 semanas": "4 weeks",
  "75 % de descuento": "75% off",
  "El costo de dos almuerzos rápidos": "The cost of two quick lunches",
  "12 semanas": "12 weeks",
  "79 % de descuento": "79% off",
  "Menos de una entrega de cena familiar": "Less than a family dinner delivery",
  "Al continuar, aceptas que, si no cancelas al menos 24 horas antes de que finalice la oferta de lanzamiento de 1 mes, se te cobrará automáticamente el precio total de": "By continuing, you agree that if you do not cancel at least 24 hours before the end of the 1-month introductory offer, you will automatically be charged the full price of",
  "cada mes hasta que canceles en": "each month until you cancel in",
  "Configuración": "Settings",
  ". Obtén más información sobre nuestra política de cancelación y reembolso en": ". Learn more about our cancellation and refund policy in",
  "Términos de suscripción": "Subscription Terms",
  "Lo que obtienes": "What you get",
  "Ahora la aplicación HARNA está disponible para": "Now the HARNA app is available for",
  "Teléfonos móviles, tabletas y televisores": "Mobile phones, tablets, and TVs",
  "APLICACIÓN HARNA": "HARNA APP",
  "Elegida por aquellos listos para transformarse": "Chosen by those ready to transform",
  "de 5": "out of 5",
  "Con la confianza de personas como tú": "Trusted by people like you",
  "Las reseñas provienen de comentarios reales de clientes en varias plataformas, con nombres y fotos modificados por motivos de privacidad": "Reviews come from real customer feedback on various platforms, with names and photos modified for privacy reasons",
  "Algunas preguntas adicionales que puedas tener": "Some additional questions you may have",
  "Obtén resultados visibles en 4 semanas!": "Get visible results in 4 weeks!",
  "Garantía de devolución del 100 % del dinero": "100% Money Back Guarantee",
  "Creemos que nuestro plan puede funcionar para usted y obtendrá resultados visibles en 4 semanas. Incluso estamos listos para reembolsarle por completo dentro de los 30 días posteriores a la compra si no obtiene resultados visibles y puede demostrar que ha seguido nuestro plan.": "We believe our plan can work for you and you will get visible results in 4 weeks. We are even ready to fully refund you within 30 days of purchase if you don't get visible results and can prove you have followed our plan.",
  "Obtenga más información sobre las limitaciones aplicables en nuestra": "Learn more about the applicable limitations in our",
  "política de devolución de dinero": "money back policy",
  "Este plan personalizado se basa en principios generales de bienestar. No es un consejo médico ni un programa de tratamiento para ninguna condición de salud": "This personalized plan is based on general wellness principles. It is not medical advice or a treatment program for any health condition",
  "Al elegir tu edad y continuar, aceptas nuestros": "By choosing your age and continuing, you agree to our",
  "Términos de servicio": "Terms of Service",
  "y reconoces nuestra": "and acknowledge our",
  "Política de cookies": "Cookie Policy",
  "Este sitio no ofrece asesoramiento médico. El contenido es solo para fines de bienestar general. Siempre consulte con un profesional de la salud antes de comenzar cualquier programa de acondicionamiento físico o si tiene alguna inquietud sobre su salud.": "This site does not offer medical advice. The content is for general wellness purposes only. Always consult with a healthcare professional before starting any fitness program or if you have any concerns about your health.",
  "bajo peso": "underweight",
  "peso normal": "normal weight",
  "sobrepeso": "overweight",
  "obesidad": "obesity",
  "Bajar de peso": "Lose weight",
  "Mantener el peso y ponerse en forma": "Maintain weight and get fit",
  "Mejorar la condición física": "Improve physical condition",
  "Aumenta la energía": "Boost energy",
  "Mejora el sueño": "Improve sleep",
  "Reduce el estrés": "Reduce stress",
  "Mejora la postura y la movilidad": "Improve posture and mobility",
  "Desarrollar la flexibilidad": "Develop flexibility",
  "Papada": "Double chin",
  "Brazos caídos": "Flabby arms",
  "Senos caídos": "Sagging breasts",
  "Grasa abdominal": "Belly fat",
  "Grasa en las rodillas": "Knee fat",
  "Alforjas": "Saddlebags",
  "Glúteos flácidos": "Sagging glutes",
  "Parte interna del muslo": "Inner thigh",
  "Delgado": "Slim",
  "Buscando ganar masa muscular": "Looking to gain muscle mass",
  "Delgado gordo": "Skinny fat",
  "Delgado, pero necesito tonificar y perder algo de peso": "Slim, but need to tone up and lose some weight",
  "Forma firme, de líneas suaves y proporciones suaves.": "Firm shape, smooth lines, and soft proportions.",
  "Sobrepeso": "Overweight",
  "¿Buscas una manera rápida y saludable de perder peso?": "Looking for a fast and healthy way to lose weight?",
  "Con curvas": "Curvy",
  "Delgada": "Slim",
  "En forma": "Fit",
  "Tonificada": "Toned",
  "Estoy bien con mi cuerpo": "I'm fine with my body",
  "Hace 1 o 2 años": "1 or 2 years ago",
  "Hace 3 a 5 años": "3 to 5 years ago",
  "Hace más de 5 años": "More than 5 years ago",
  "Nunca": "Never",
  "Espalda sensible": "Sensitive back",
  "Rodillas sensibles": "Sensitive knees",
  "Cirugía de cadera": "Hip surgery",
  "Hombros y brazos": "Shoulders and arms",
  "Pantorrillas y tobillos": "Calves and ankles",
  "Dolor/Malestar": "Pain/Discomfort",
  "Alguna dificultad": "Some difficulty",
  "Cómodo": "Comfortable",
  "Comunidad de mujeres": "Women's community",
  "Mujer fitness": "Fitness woman",
  "Peso": "Weight",
  "kilogramo": "kilogram",
  "libras": "pounds",
  "Tu edad": "Your age",
  "Ejercicios suaves y adaptados": "Gentle and adapted exercises",
  "Apoyo profesional": "Professional support",
  "Enfoque personalizado": "Personalized approach",
  "Explicación de los beneficios para la salud": "Explanation of health benefits",
  "Tranquilo y relajado": "Calm and relaxed",
  "Mayormente en casa, disfrutando de un ritmo más lento y tranquilo": "Mostly at home, enjoying a slower and calmer pace",
  "Hogar y niños": "Home and kids",
  "Cuidar a la familia y mantenerse moderadamente activo": "Taking care of the family and staying moderately active",
  "Activo y social": "Active and social",
  "Las caminatas regulares y las actividades sociales te mantienen en movimiento": "Regular walks and social activities keep you moving",
  "Tonificar": "Tone",
  "Mejorar salud": "Improve health",
  "Tranquilo": "Calm",
  "Hogar": "Home",
  "Activo": "Active",
  "Reduce el estrés y equilibra tu vida": "Reduce stress and balance your life",
  "Afina tus músculos, incluso los ocultos": "Refine your muscles, even the hidden ones",
  "Resistencia": "Resistance",
  "Trabaja esos músculos para fortalecerlos": "Work those muscles to strengthen them",
  "Caminar": "Walking",
  "Energiza tu cuerpo, fortalece cada paso": "Energize your body, strengthen every step",
  "Solo tengo café o té": "I only have coffee or tea",
  "Aproximadamente 2 vasos (0,5 L)": "About 2 glasses (0.5 L)",
  "2 a 6 vasos (0,5-1,5 L)": "2 to 6 glasses (0.5-1.5 L)",
  "Más de 6 vasos": "More than 6 glasses",
  "Sin restricciones": "No restrictions",
  "Abierto a todos los alimentos": "Open to all foods",
  "Soy vegetariano": "I am vegetarian",
  "Verduras, cereales, pero sin carne animal": "Vegetables, grains, but no animal meat",
  "Soy vegano": "I am vegan",
  "Puramente a base de plantas, sin productos animales": "Purely plant-based, no animal products",
  "Sin gluten": "Gluten-free",
  "Excluye productos de cereales que contengan gluten": "Excludes cereal products containing gluten",
  "Sin lactosa": "Lactose-free",
  "Excluir productos lácteos": "Exclude dairy products",
  "Dieta cetogénica": "Ketogenic diet",
  "Dieta baja en carbohidratos y alta en grasas": "Low-carb, high-fat diet",
  "Procrastinación": "Procrastination",
  "Alimentación poco saludable": "Unhealthy eating",
  "Redes sociales": "Social media",
  "Beber demasiada cafeína": "Drinking too much caffeine",
  "Atracón de series": "Binge-watching",
  "Dudas sobre uno mismo": "Self-doubt",
  "Morderse las uñas": "Nail-biting",
  "Llegar tarde": "Being late",
  "Fumar": "Smoking",
  "Beber alcohol": "Drinking alcohol",
  "Matrimonio o una relación": "Marriage or a relationship",
  "Trabajo o vida familiar ajetreados": "Busy work or family life",
  "Estrés o salud mental": "Stress or mental health",
  "Inicio de la menopausia": "Onset of menopause",
  "Trastorno por medicamentos": "Medication disorder",
  "Recupera tu cuerpo": "Get your body back",
  "¡Me encanta esta aplicación! Llevo seis meses usándola y he visto resultados reales. Las instrucciones son claras y fáciles de seguir": "I love this app! I've been using it for six months and have seen real results. The instructions are clear and easy to follow",
  "Nunca me han gustado los entrenamientos estructurados, pero esto es más fácil de lo que esperaba. Estoy empezando, pero tengo buenas vibras": "I've never liked structured workouts, but this is easier than I expected. I'm just starting, but I have good vibes",
  "Como madre de dos hijos, encontrar tiempo para hacer ejercicio era imposible, hasta que apareció HarnaFit. Sus entrenamientos rápidos y efectivos se adaptan perfectamente a mi día. Incluso si solo tengo 15 minutos, puedo hacer una sesión y sentirme realizada": "As a mother of two, finding time to exercise was impossible, until HarnaFit came along. Its quick and effective workouts fit perfectly into my day. Even if I only have 15 minutes, I can do a session and feel accomplished",
  "Por favor, introduce tu correo electrónico.": "Please enter your email.",
  "Por favor, introduce un correo electrónico válido.": "Please enter a valid email.",
  "Tu nombre": "Your name",
  "Amiga": "Friend",
  "Programa personalizado adaptado a las necesidades cambiantes de las mujeres mayores de 40 años.": "Personalized program adapted to the changing needs of women over 40.",
  "Movimiento consciente para reducir el estrés, mejorar el estado de ánimo y mejorar el sueño": "Mindful movement to reduce stress, improve mood, and enhance sleep",
  "Muévase libremente y con confianza, sin dolor ni molestias.": "Move freely and confidently, without pain or discomfort.",
  "Fortalecimiento del core y la espalda para aliviar el dolor de espalda y mejorar la postura.": "Core and back strengthening to relieve back pain and improve posture.",
  "¿Qué ejercicios incluye Pilates?": "What exercises does Pilates include?",
  "Pilates incluye una variedad de ejercicios de bajo impacto enfocados en la fuerza del core, flexibilidad y control muscular.": "Pilates includes a variety of low-impact exercises focused on core strength, flexibility, and muscle control.",
  "¿Cómo puedo saber qué programa es adecuado para mí?": "How can I know which program is right for me?",
  "Basado en tus respuestas al cuestionario, hemos creado un plan personalizado que se adapta a tu nivel de experiencia, objetivos y necesidades físicas.": "Based on your answers to the questionnaire, we have created a personalized plan that adapts to your experience level, goals, and physical needs.",
  "¿Cómo accedo a mi plan?": "How do I access my plan?",
  "Una vez que completes tu registro, podrás descargar nuestra aplicación y acceder a tu plan completo desde cualquier dispositivo.": "Once you complete your registration, you can download our app and access your full plan from any device.",
  "Ocultar Navegación": "Hide Navigation",
  "Mostrar Navegación": "Show Navigation",
  "Siguiente paso": "Next step",
  "Continuar": "Continue",
  "Sí, lo hago a veces.": "Yes, I do sometimes.",
  "Sí, pero hace un tiempo.": "Yes, but it's been a while.",
  "No, no tengo experiencia.": "No, I have no experience."
};

let content = fs.readFileSync('src/App.tsx', 'utf-8');

// Sort by length descending to replace longer strings first
const keys = Object.keys(dictionary).sort((a, b) => b.length - a.length);

for (const key of keys) {
  // Use a global regex to replace all occurrences
  // Escape special characters in key
  const escapedKey = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const regex = new RegExp(escapedKey, 'g');
  content = content.replace(regex, dictionary[key]);
}

fs.writeFileSync('src/App.tsx', content, 'utf-8');
console.log('Done translating src/App.tsx');
